# Generated by Django 2.2.3 on 2019-07-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('available', models.BooleanField()),
                ('Image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
